import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('.cache/screenshots', { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.locator('.portrait-stage[data-loaded="true"]').waitFor({ timeout: 60000 });
await page.locator('[data-pause]').click();
await page.screenshot({ path: '.cache/screenshots/home-desktop.png', fullPage: false });
console.log('Portrait loaded.');
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(500);
await page.screenshot({ path: '.cache/screenshots/home-mobile.png' });
console.log('Mobile overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
await page.setViewportSize({ width: 1440, height: 1100 });
await page.goto('http://127.0.0.1:5173/#/gala');
await page.locator('.gallery-stage[data-loaded="7"]').waitFor({ timeout: 120000 });
await page.screenshot({ path: '.cache/screenshots/gala-desktop.png' });
await page.locator('[data-next]').click();
await page.waitForTimeout(1800);
await page.screenshot({ path: '.cache/screenshots/gala-detail.png' });
console.log('All seven sculptures loaded. Selected:', await page.locator('[data-sculpture-title]').textContent());
await writeFile('.cache/browser-errors.json', JSON.stringify(errors, null, 2));
console.log('Browser errors:', errors);
await browser.close();
