import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
await mkdir('.cache/screenshots', { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' });
await page.locator('.portrait-stage[data-loaded="true"]').waitFor({ timeout: 60000 });
if (await page.locator('.orbit-link').count() !== 9) throw new Error('Home highlights are missing');
if (!await page.locator('.intro-sub').textContent().then(t => t.includes('pipeline to generate my head with neural networks'))) throw new Error('Head-generation line is missing');
if (!await page.locator('.intro-orbit').textContent().then(t => t.includes('revolves around my head right now'))) throw new Error('Orbit introduction is missing');
if (!await page.locator('.intro-created').textContent().then(t => t.includes('Created in 3D'))) throw new Error('3D portrait label is missing');
await page.locator('[data-pause]').click();
const desktopOverlap = await page.evaluate(() => { const copy = [...document.querySelectorAll('.hero-intro h1,.hero-intro p')].map(e => e.getBoundingClientRect()); return [...document.querySelectorAll('.orbit-link')].some(e => { const r = e.getBoundingClientRect(); return copy.some(c => r.left < c.right && r.right > c.left && r.top < c.bottom && r.bottom > c.top); }); });
if (desktopOverlap) throw new Error('Hero copy overlaps orbit navigation on desktop');
await page.screenshot({ path: '.cache/screenshots/home-desktop.png', fullPage: false });
for (const size of [{ width: 1884, height: 770 }, { width: 1507, height: 616 }, { width: 1440, height: 650 }]) {
  await page.setViewportSize(size);
  await page.waitForTimeout(250);
  const firstScreen = await page.evaluate(() => {
    const headStage = document.querySelector('.portrait-stage').getBoundingClientRect();
    const awards = [...document.querySelectorAll('.orbit-link')].map(el => el.getBoundingClientRect());
    const copy = [...document.querySelectorAll('.hero-intro h1,.hero-intro p')].map(e => e.getBoundingClientRect());
    const overlap = [...document.querySelectorAll('.orbit-link')].some(e => { const r = e.getBoundingClientRect(); return copy.some(c => r.left < c.right && r.right > c.left && r.top < c.bottom && r.bottom > c.top); });
    return { stageVisible: headStage.top < innerHeight / 2 && headStage.bottom <= innerHeight, awardsVisible: awards.every(r => r.top >= 100 && r.bottom <= innerHeight && r.left >= 0 && r.right <= innerWidth), overlap };
  });
  if (!firstScreen.stageVisible || !firstScreen.awardsVisible || firstScreen.overlap) throw new Error(`Short desktop hero failed at ${size.width}x${size.height}: ${JSON.stringify(firstScreen)}`);
  await page.screenshot({ path: `.cache/screenshots/home-${size.width}x${size.height}.png` });
}
console.log('Portrait loaded.');
await page.evaluate(() => scrollTo(0, 0));
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(500);
const mobileOverlap = await page.evaluate(() => { const copy = [...document.querySelectorAll('.hero-intro h1,.hero-intro p')].map(e => e.getBoundingClientRect()); return [...document.querySelectorAll('.orbit-link')].some(e => { const r = e.getBoundingClientRect(); return copy.some(c => r.left < c.right && r.right > c.left && r.top < c.bottom && r.bottom > c.top); }); });
if (mobileOverlap) throw new Error('Hero copy overlaps orbit navigation on mobile');
await page.screenshot({ path: '.cache/screenshots/home-mobile.png' });
await page.locator('.home-hero').scrollIntoViewIfNeeded();
await page.screenshot({ path: '.cache/screenshots/home-hero-mobile.png' });
console.log('Mobile overflow:', await page.evaluate(() => document.documentElement.scrollWidth > innerWidth));
await page.goto('http://127.0.0.1:5173/#/equity');
await page.locator('[data-equity-tab]').nth(1).click();
if (!await page.locator('#equity-panel').textContent().then(t => t.includes('80,000'))) throw new Error('ConvoAAVE panel did not open');
if (await page.locator('.equity-media').isVisible()) throw new Error('ConvoAAVE must be text-only');
await page.screenshot({ path: '.cache/screenshots/equity-text-mobile.png' });
await page.locator('[data-equity-tab]').nth(2).click();
if (!await page.locator('#equity-panel h2').textContent().then(t => t === 'Student AI Squad')) throw new Error('Student AI Squad was not renamed');
if (await page.locator('.equity-media').isVisible()) throw new Error('Student AI Squad must be text-only');
await page.locator('[data-equity-tab]').first().click();
const firstPhoto = await page.locator('.equity-photo-image').getAttribute('src');
await page.locator('[data-slide-next]').click();
if (firstPhoto === await page.locator('.equity-photo-image').getAttribute('src')) throw new Error('Equity photograph did not advance');
if (!await page.locator('.equity-photo-image').getAttribute('src').then(s => s.includes('/machina-mundi/'))) throw new Error('Non-Machina photograph shown');
await page.locator('.equity-photo-image').evaluate(img => img.decode());
if (await page.evaluate(() => document.documentElement.scrollHeight > innerHeight + 2)) throw new Error('Equity page scrolls on mobile');
await page.screenshot({ path: '.cache/screenshots/equity-mobile.png' });
await page.setViewportSize({ width: 1440, height: 900 });
if (await page.evaluate(() => document.documentElement.scrollHeight > innerHeight + 2)) throw new Error('Equity page scrolls on desktop');
await page.screenshot({ path: '.cache/screenshots/equity-desktop.png' });
console.log('Equity tabs, rotating images, and single-screen layout verified.');
await page.goto('http://127.0.0.1:5173/#/projects');
await page.locator('[data-project="corporations"]').click();
if (!await page.locator('#dialog-title').textContent().then(t => t.includes('Scholastic Gold Medal'))) throw new Error('Scholastic distinction missing from project name');
const essayLink = page.locator('.project-detail a', { hasText: 'Read the Gold Medal essay' });
const essayUrl = await essayLink.getAttribute('href');
if (essayUrl !== 'https://github.com/karthiksrikumar/personalwebsite/blob/main/we-the-corporations.pdf') throw new Error('The main-branch essay PDF is not linked');
await page.locator('.dialog-close').click();
console.log('Essay PDF link verified.');
await page.setViewportSize({ width: 1440, height: 1100 });
await page.goto('http://127.0.0.1:5173/#/gala');
await page.locator('.gallery-stage[data-loaded="7"]').waitFor({ timeout: 120000 });
if (!await page.locator('.gala-intro').textContent().then(t => t.includes('using CAD') && t.includes('digital medium'))) throw new Error('Gala introduction is missing');
await page.screenshot({ path: '.cache/screenshots/gala-desktop.png' });
await page.locator('[data-tour]').click();
await page.waitForTimeout(850);
const galaHeader = await page.locator('.gala-heading').boundingBox();
const siteHeader = await page.locator('.site-header').boundingBox();
if (!galaHeader || galaHeader.y < 98 || galaHeader.y > 500 || !siteHeader || siteHeader.y !== 0) throw new Error('Gala headers are hidden after entering');
await page.screenshot({ path: '.cache/screenshots/gala-entered.png' });
await page.locator('[data-next]').click();
await page.waitForTimeout(1800);
await page.screenshot({ path: '.cache/screenshots/gala-detail.png' });
console.log('All seven sculptures loaded. Selected:', await page.locator('[data-sculpture-title]').textContent());
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://127.0.0.1:5173/#/gala');
await page.locator('.gallery-stage[data-loaded="7"]').waitFor({ timeout: 120000 });
await page.screenshot({ path: '.cache/screenshots/gala-mobile.png' });
await page.locator('[data-tour]').click();
await page.waitForTimeout(850);
const mobileGalaHeader = await page.locator('.gala-heading').boundingBox();
const mobileSiteHeader = await page.locator('.site-header').boundingBox();
if (!mobileGalaHeader || mobileGalaHeader.y < 112 || !mobileSiteHeader || mobileSiteHeader.y !== 0) throw new Error('Mobile gala header is hidden after entering');
await page.screenshot({ path: '.cache/screenshots/gala-mobile-entered.png' });
await writeFile('.cache/browser-errors.json', JSON.stringify(errors, null, 2));
console.log('Browser errors:', errors);
await browser.close();
