import { execFileSync } from 'node:child_process';
import { mkdir, cp, writeFile, access, readdir, rm } from 'node:fs/promises';
import path from 'node:path';
const root = process.cwd();
const directory = path.resolve(root, '.cache/pages-publish');
if (!directory.startsWith(path.resolve(root, '.cache') + path.sep)) throw new Error('Invalid generated deployment directory');
const marker = path.join(directory, '.generated-deployment');
await mkdir(directory, { recursive: true });
const git = (...args) => execFileSync('git', ['-c', `safe.directory=${directory.replaceAll('\\', '/')}`, '-c', 'credential.helper=', '-c', 'credential.helper=!gh auth git-credential', ...args], { cwd: directory, stdio: 'inherit' });
let initialized = false;
try { await access(marker); initialized = true; } catch { /* Initialize a dedicated generated checkout below. */ }
if (!initialized) {
  if ((await readdir(directory)).length) throw new Error('Refusing to use an unmarked nonempty deployment directory');
  git('init', '-b', 'gh-pages');
  git('remote', 'add', 'origin', 'https://github.com/karthiksrikumar/personalwebsite.git');
  await writeFile(marker, 'Generated by scripts/publish-pages.mjs. Do not store source files here.\n');
  await writeFile(path.join(directory, '.gitignore'), '.generated-deployment\n');
}
// This marked directory contains only generated output and its own Git checkout.
for (const name of await readdir(directory)) {
  if (['.git', '.gitignore', '.generated-deployment'].includes(name)) continue;
  const target = path.resolve(directory, name);
  if (!target.startsWith(directory + path.sep)) throw new Error('Invalid generated asset path');
  await rm(target, { recursive: true, force: true });
}
await cp(path.join(root, 'dist'), directory, { recursive: true });
await writeFile(path.join(directory, '.nojekyll'), '');
git('add', '--all');
try { git('diff', '--cached', '--quiet'); console.log('No deployment changes.'); } catch { git('commit', '-m', 'Publish personal website'); }
git('push', '-u', 'origin', 'gh-pages');
