export const projects = [
  { id: 'oatnet', title: 'OATNet', type: 'Machine learning', image: 'previews/oatnet.svg', subtitle: 'Doing more with fewer computations.', description: 'A neural network architecture that decomposes dense weights into a ternary matrix and a rank-one magnitude approximation. The work investigates how much computation can be removed while preserving useful model performance.', awards: ['Regeneron ISEF finalist, 2025', '$30,000 Quinnipiac University Award for Excellence in Computing', '2nd place, Physical Sciences, Connecticut Science & Engineering Fair 2025'], links: [['ISEF project', 'https://isef.net/project/robo036-oatnet-ternary-based-neural-network-optimization']] },
  { id: 'corporations', title: 'We the Corporations', type: 'Political writing', image: 'previews/we-the-corporations.svg', subtitle: 'Plutocratic Power and the Managed Fragmentation of the Public', description: 'An argument that campaign finance, partisan media, and engineered cultural conflict allow concentrated wealth to weaken democratic representation. Written at South Windsor High School.', awards: ['Scholastic National Gold Medal'], links: [['Read the essay', 'papers/we-the-corporations.pdf']] },
  { id: 'subtraction-games', title: 'Exponential periods in finite subtraction games', type: 'Mathematics', image: 'previews/subtraction-games.png', subtitle: 'Long patterns from a finite set of moves.', description: 'Mathematical work on periodic behavior in finite subtraction games. The paper and supporting code are available in the project repository.', links: [['Read the paper', 'papers/subtraction-games.pdf'], ['Code & proofs', 'https://github.com/karthiksrikumar/Exponential-Periods-in-Finite-Subtraction-Games']] },
  { id: 'driveaeye', title: 'DriveAEye', type: 'Accessible technology', image: 'previews/driveaeye.jpg', subtitle: 'An extra pair of eyes on the road.', description: 'A mobile road-safety app with real-time object detection and auditory alerts. It brings driver-assistance features to a phone, with an emphasis on making those tools more accessible.', awards: ['2024 Congressional App Challenge winner, Connecticut’s 1st District', 'National Invention Convention participant'], links: [['Congressional App Challenge', 'https://www.congressionalappchallenge.us/24-CT01/']] },
  { id: 'babyvlm', title: 'BabyVLM', type: 'Vision & language', image: 'previews/babyvlm.svg', subtitle: 'Boston University RISE research under Professor Boqing Gong.', description: 'Vision-language research conducted through Boston University’s Research in Science and Engineering (RISE) program under Professor Boqing Gong. The RISE internship had a 2.2% acceptance rate.', awards: ['Boston University RISE research intern'], links: [['Boqing Gong’s lab', 'https://boqinggong.info/']] },
  { id: 'safenet', title: 'SafeNet AI', type: 'AI safety', image: 'previews/safenet.svg', subtitle: 'A project in applied AI safety.', description: 'An AI project recognized in the Presidential AI Challenge.', awards: ['Presidential AI Challenge State Champion'], links: [] },
];

export const papers = [
  { id: 'ntk', year: '2025', title: 'On the Relationship Between Neural Tangent Kernel Frobenius Distance and Distillation Sample Complexity', authors: 'Arnav Sharma, Ahmed Wez, Karthik Srikumar', venue: 'Lock-LLM Workshop at NeurIPS 2025', description: 'Relating the distance between teacher and student neural tangent kernels to the difficulty of knowledge distillation.', url: 'https://openreview.net/forum?id=UpMG1bPKSB', preview: 'previews/ntk.svg', pdf: 'https://openreview.net/attachment?id=UpMG1bPKSB&name=pdf', featured: true },
  { id: 'oromo', year: '2026', title: 'Robust Tokenization for Low-Resource Oromo Medical Texts via Novel Lightweight Augmentation', authors: 'Karthik Srikumar', venue: 'AI for African Languages Conference · PMLR 314, pp. 50–55', description: 'Rule-based augmentation for more consistent tokenization of Afaan Oromo medical text.', url: 'https://proceedings.mlr.press/v314/srikumar26a.html', preview: 'previews/oromo.png', actualPreview: true, pdf: 'papers/oromo.pdf' },
  { id: 'euhr', year: '2025', title: 'E-UHR: An Ethical Uncertainty Handling and Response Framework for Embodied AI Co-Habitats', authors: 'Karthik Srikumar', venue: 'Human-aware Embodied AI Workshop at IROS 2025', description: 'A framework for handling uncertainty when robots and people share spaces.', url: 'https://heai-iros25-workshop.github.io/', preview: 'previews/euhr.svg', pdf: 'https://openreview.net/pdf?id=BvImRZyNf5' },
  { id: 'reasoning', year: '2025', title: 'Information-Theoretic Bounds on Multi-Step Reasoning: When is Chain-of-Thought Provably Necessary?', authors: 'Karthik Srikumar', venue: 'Workshop on Efficient Reasoning at NeurIPS 2025', description: 'Studying when intermediate reasoning steps provide an advantage over direct prediction.', url: 'https://neurips.cc/virtual/2025/126586', preview: 'previews/reasoning.svg', pdf: 'https://openreview.net/pdf?id=l8VMwSaOGL' },
  { id: 'tempirl', year: '2025', title: 'TEMPiRL: Foundational Compounding Temporal Drift Theory for Temporal-Graph Adaptation in Large Language Models', authors: 'Arnav Sharma, Karthik Srikumar', venue: 'AI That Keeps Up Workshop at NeurIPS 2025', description: 'Temporal drift and adaptation in language models as the world changes around their training data.', url: 'https://openreview.net/forum?id=Dux58yUgUC', preview: 'previews/tempirl.svg', pdf: 'https://openreview.net/attachment?id=Dux58yUgUC&name=pdf' },
];

export const sculptures = [
  { id: 'capitol-marionette', title: 'Capitol marionette', category: 'Power & public life', description: 'The Capitol hangs beneath visible strings, its dome intact even as its independence disappears. The piece argues that democratic architecture can preserve the appearance of public authority while private hands dictate its movements. Walk around it: the gap between the building and its unseen operator is the space where accountability ought to live.' },
  { id: 'capitol-at-auction', title: 'Capitol at auction', category: 'Power & public life', description: 'The Capitol is presented as a lot for sale, shrinking a common institution to the scale of private property. This is a thesis about political capture: when access is priced, representation stops being a right shared equally and becomes an asset distributed to the highest bidder.' },
  { id: 'price-of-power', title: 'The price of power', category: 'Power & public life', description: 'Flames consume the Capitol while banknotes remain suspended above it and pale figures gather below. The work asks who survives a crisis of government and who pays for it. Wealth circulates undisturbed; the institution meant to answer to the public is the thing allowed to burn.' },
  { id: 'machina-mundi', title: 'Machina Mundi', category: 'Emblems & structures', description: 'An emblem becomes a three-dimensional system of interlocking parts. Its meaning shifts as the viewer moves, refusing a single fixed angle. That instability is the argument: technology presented as neutral is always arranged by human choices about who can enter, who is represented, and who remains outside the frame.' },
  { id: 'south-windsor-high-school', title: 'South Windsor High School', category: 'Familiar places', description: 'From overhead, the school is a tidy institutional plan; at ground level, it becomes a place where policy is lived. The model treats public education as civic infrastructure, not merely a building: decisions about access, resources, and belonging become concrete in its corridors and classrooms.' },
  { id: 'stadium', title: 'Stadium', category: 'Familiar places', description: 'Concentric tiers face a shared center, but no crowd fills them. The empty seats frame a question about collective life: who gets invited into public spectacle, who remains outside, and what happens when belonging is organized by the price of admission?' },
  { id: 'blocky-cow', title: 'Blocky cow', category: 'Small departures', description: 'A cow assembled from blunt geometric blocks interrupts the monumental buildings. Its humor makes a quieter point: political imagination needs room for the ordinary, the absurd, and the living things that grand institutions so often reduce to abstractions.' },
];
